print("Multiplicação de Escalar Real por Vetor:")
print("Coordenadas do vetor u:")
a = float(input("Digite a 1a. coordenada: "))
b = float(input("Digite a 2a. coordenada: "))
c = float(input("Digite a 3a. coordenada: "))
k = float(input("Digite o valor de k: "))
print("Vetor: ({:.2f}, {:.2f}, {:.2f})".format((a*k),(b*k),(c*k)))